# Generated by Django 5.0.6 on 2026-05-18 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_correct', models.PositiveIntegerField()),
                ('score_total', models.PositiveIntegerField()),
                ('accuracy_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_taken_sec', models.PositiveIntegerField()),
                ('xp_earned', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_record',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveSmallIntegerField()),
                ('question_text', models.CharField(max_length=256)),
                ('expected_answer', models.IntegerField()),
                ('submitted_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('elapsed_ms', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_question_attempt',
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SESSION_COMPLETE', 'Session Complete'), ('STREAK_BONUS', 'Streak Bonus'), ('LEVEL_UP', 'Level Up'), ('PERFECT_SCORE', 'Perfect Score'), ('FIRST_ATTEMPT', 'First Attempt Bonus')], max_length=32)),
                ('delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_xp_event',
            },
        ),
        migrations.CreateModel(
            name='LevelCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLASSWORK', 'Classwork'), ('HOMEWORK', 'Homework')], max_length=16)),
                ('first_completed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.level')),
            ],
            options={
                'db_table': 'progress_level_completion',
            },
        ),
    ]
