# Generated by Django 5.0.6 on 2026-05-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levelcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_record', to='exercises.arenasession'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelcompletion',
            name='best_progress_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_completions', to='progress.progressrecord'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.arenasession'),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.arenasession'),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='progressrecord',
            index=models.Index(fields=['user', '-created_at'], name='progress_re_user_id_0622fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='levelcompletion',
            unique_together={('user', 'level', 'kind')},
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['session', 'question_index'], name='progress_qu_session_62ddc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('session', 'question_index')},
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', '-created_at'], name='progress_xp_user_id_ca11a5_idx'),
        ),
    ]
