# Generated by Django 5.0.6 on 2026-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_question_attempt_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='is_skip',
            field=models.BooleanField(default=False),
        ),
    ]
