# Generated by Django 5.0.6 on 2026-05-18 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CLASSWORK', 'Classwork'), ('HOMEWORK', 'Homework'), ('FLASH_CARDS', 'Flash Cards'), ('ZEN', 'Zen Mode'), ('TIME_ATTACK', 'Time Attack'), ('CUSTOM', 'Custom Challenge')], max_length=16)),
                ('config_json', models.JSONField()),
                ('seed', models.BigIntegerField()),
                ('questions_json', models.JSONField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exercises_arena_session',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLASSWORK', 'Classwork'), ('HOMEWORK', 'Homework')], max_length=16)),
                ('question_count', models.PositiveSmallIntegerField(default=30)),
                ('time_limit_sec', models.PositiveIntegerField(default=600)),
                ('config_json', models.JSONField()),
            ],
            options={
                'db_table': 'exercises_template',
            },
        ),
    ]
