# Generated by Django 5.0.6 on 2026-05-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arenasession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisetemplate',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='arenasession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.exercisetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisetemplate',
            unique_together={('lesson', 'kind')},
        ),
        migrations.AddIndex(
            model_name='arenasession',
            index=models.Index(fields=['user', '-started_at'], name='exercises_a_user_id_81be08_idx'),
        ),
    ]
