# Generated by Django 5.0.6 on 2026-06-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_level_xp_thresholds'),
        ('exercises', '0003_arenasession_is_test_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('topic_name', models.CharField(blank=True, max_length=256)),
                ('question_text', models.CharField(max_length=512)),
                ('operator', models.CharField(blank=True, max_length=16)),
                ('answer', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_questions', to='courses.lesson')),
            ],
            options={
                'db_table': 'exercises_curated_question',
                'ordering': ['row_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='curatedquestion',
            constraint=models.UniqueConstraint(fields=('lesson', 'row_index'), name='exercises_curatedquestion_lesson_row_unique'),
        ),
    ]
