# Generated by Django 5.0.6 on 2026-10-01 13:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_curatedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_date', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('source_level_id', models.UUIDField()),
                ('source_lesson_id', models.PositiveIntegerField()),
                ('source_template_id', models.PositiveIntegerField()),
                ('level_name', models.CharField(max_length=64)),
                ('level_order', models.PositiveSmallIntegerField()),
                ('lesson_name', models.CharField(max_length=64)),
                ('lesson_order', models.PositiveSmallIntegerField()),
                ('config_json', models.JSONField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='daily_quest', to='exercises.arenasession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises_daily_quest',
            },
        ),
        migrations.AddConstraint(
            model_name='dailyquest',
            constraint=models.UniqueConstraint(fields=('user', 'mission_date'), name='dailyquest_user_date_unique'),
        ),
    ]
