# Generated by Django 5.0.6 on 2026-06-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='class',
            name='live_session_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
