# Generated by Django 5.0.6 on 2026-06-29 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_add_join_code_and_live_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(default='teacher_attested', max_length=32)),
                ('student_dob', models.DateField()),
                ('under_13', models.BooleanField()),
                ('attested_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('EU', 'European Union'), ('IN', 'India'), ('OTHER', 'Other')], default='OTHER', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_attestations', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='classroom.enrollment')),
            ],
            options={
                'db_table': 'classroom_enrollment_consent',
            },
        ),
    ]
