# Generated by Django 5.0.6 on 2026-05-18 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'courses_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('xp_threshold', models.PositiveIntegerField(default=0)),
                ('is_advanced', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'courses_level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video URL'), ('IMAGE', 'Image')], max_length=8)),
                ('order', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson')),
            ],
            options={
                'db_table': 'courses_content_block',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.level'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('level', 'order')},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLASSWORK', 'Classwork'), ('HOMEWORK', 'Homework')], max_length=16)),
                ('file', models.FileField(upload_to='materials/%Y/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.level')),
            ],
            options={
                'db_table': 'courses_material',
                'unique_together': {('level', 'kind', 'version')},
            },
        ),
    ]
