# Generated by Django 5.0.6 on 2026-05-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('lesson', 'order')},
        ),
    ]
